### ISSUE TITLE
GitHubログインが出来ない

### ISSUE THREAD

**Issue by kou72** [AkiUnleash/hands-on-nextjs-supabase#21]
GitHubログインが出来ないようになっていました。
ドメインの期限切れか何かですかね？

![issue](https://user-images.githubusercontent.com/40513273/143665064-6d22ce04-8190-41bd-a124-b18bc5d7ca63.gif)

### ブラウザ表示

> このサイトにアクセスできませんqcehnbmudipnctaxbjtp.supabase.co にタイプミスがないか確認してください。
> タイプミスでない場合は、Windows ネットワーク診断をお試しください。
> DNS_PROBE_FINISHED_NXDOMAIN

**Comment by AkiUnleash** [comment]
Supabaseを一定時間しようしていないと、無料プランの場合休止状態になるようです。
※ 復帰させて、ご確認いただきました。(2021/11/27)
